PROJNAME:=demo
EXEDIR:=../bin
LINK_FLAGS:=-L../lib -L/usr/local/lib -L/usr/lib/i386-linux-gnu -lengine -lpthread -lSDL
COMPILE_FLAGS:=-I../include -I/usr/local/include/assimp -I/usr/include/SDL -I/usr/include/ImageMagick -DARCH_X86=1 
COMPILE_FILES:=demo.cpp
include ../Makefile-exe
